### ISSUE TITLE
desktop wallet in dev mode on ubuntu launches, but all clicks are ignored

### ISSUE THREAD

**Issue by max-l** [Block-Equity/desktop-wallet#62]
I did a source install as described in the readme, version  "commit de3bca708a10750f4c49eaf1ff784ef26b43e58a" 

and lauched with "npm run dev", 

I see the wallet launching, with 2 buttons (create wallet and resore wallet),
nothing happens if I click on either or them... 

running on ubuntu 18.04 
nom 6.9.0
node 8.15.0

Note that there were many warnings during the build: 

```
 npm install 

> electron-react-boilerplate@0.13.2 postinstall /home/maxou/dev/chartalis/desktop-wallet
> node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json


> electron-react-boilerplate@0.13.2 flow-typed /home/maxou/dev/chartalis/desktop-wallet
> rimraf flow-typed/npm && flow-typed install --overwrite || true

• Found 104 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: fuzzaldrin-plus_v0.6.0/CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named `fuzzaldrin-plus_v0.6.0.js`.
    at validationError (/home/maxou/dev/chartalis/desktop-wallet/node_modules/flow-typed/dist/lib/validationErrors.js:14:11)
    at /home/maxou/dev/chartalis/desktop-wallet/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:113:53
    at Array.forEach (<anonymous>)
    at extractLibDefsFromNpmPkgDir$ (/home/maxou/dev/chartalis/desktop-wallet/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:95:23)
    at tryCatch (/home/maxou/dev/chartalis/desktop-wallet/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/maxou/dev/chartalis/desktop-wallet/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/maxou/dev/chartalis/desktop-wallet/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/home/maxou/dev/chartalis/desktop-wallet/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/home/maxou/dev/chartalis/desktop-wallet/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:155:20)
    at /home/maxou/dev/chartalis/desktop-wallet/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:165:13

> electron-react-boilerplate@0.13.2 build-dll /home/maxou/dev/chartalis/desktop-wallet
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors

Hash: d1f277e6209039627fdd
Version: webpack 3.11.0
Time: 7306ms
              Asset     Size  Chunks                    Chunk Names
renderer.dev.dll.js  9.09 MB       0  [emitted]  [big]  renderer
[./node_modules/config/lib recursive] ./node_modules/config/lib 160 bytes {0} [built]
[./node_modules/electron-debug recursive] ./node_modules/electron-debug 160 bytes {0} [built]
[./node_modules/moment/locale recursive ^\.\/.*$] ./node_modules/moment/locale ^\.\/.*$ 2.88 kB {0} [optional] [built]
[./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 596 bytes {0} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
   [0] dll renderer 12 bytes {0} [built]
    + 2150 hidden modules

WARNING in ./node_modules/config/lib/config.js
1004:28-45 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
1035:16-34 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
1044:14-32 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
1052:14-32 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
1060:13-30 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
1067:13-30 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
1078:16-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
1084:12-28 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/electron-debug/index.js
81:45-58 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer

WARNING in ./node_modules/electron-debug/index.js
84:85-106 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
890:21-42 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
894:8-23 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
904:21-42 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
922:17-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
930:21-42 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
933:13-30 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
999:15-35 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js
 @ dll renderer

WARNING in ./node_modules/config/lib/config.js
require.extensions is not supported by webpack. Use a loader instead.
 @ dll renderer
  • electron-builder version=19.56.0
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=linux arch=x64 appDir=/home/maxou/dev/chartalis/desktop-wallet/app
npm WARN postcss-html@0.12.0 requires a peer of postcss-less@>=1.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-html@0.12.0 requires a peer of sugarss@>=1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 26129 packages in 39.176s
found 931 vulnerabilities (125 low, 702 moderate, 102 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

```

**Comment by pooyaho** [comment]
Also I've this problem
